### ISSUE TITLE
[WM-Bus] Water meters sometimes went offline "wrong keys"

### ISSUE THREAD

**Issue by JensHoRi** [ConnectorIO/connectorio-addons#47]
Device got already actual data went suddenly to offline "wrong keys". Save configuration (change in label eg) let it come online again

Maybe only a onetime issue, if no further notices like this could be closed again.

**Comment by splatch** [comment]
It could happen because binding calculates device address from provided data (serial number, manufacturer etc) which then is matched against device address reported over serial interface. Key is registered with first address which might require tweaking. I’d wait until #45 so we will have a way to compare frame and key assignment in binding code.

**Comment by JensHoRi** [comment]
I believe was a one time only situation

**Comment by splatch** [comment]
Under the neath all keys are shared because they are being held by library within serial or tcp connection. This means that in case of miss-configuration or two things having same device address but different encryption keys one will work and other will fail.
